"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { Icon } from "../components/Icon";
import { OperationDisclosure } from "../components/OperationDisclosure";
import { PageHeader } from "../components/PageHeader";

const apiBase = process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://localhost:8080";
type Permission = { code: string };
type Me = { permissions: Permission[] };
type AuthResponse = { accessToken: string; accessTokenExpiresAt: string };
type Company = { id: string; code: string; name: string; defaultCurrency: string };
type Employee = { id: string; companyId: string; employeeNo: string; firstName: string; lastName: string; status: string };
type EmployeePage = { items: Employee[] };
type Location = { id: string; companyId: string; code: string; name: string; isActive: boolean; version: number };
type StockItem = { id: string; companyId: string; code: string; name: string; unit: string; minimumLevel: number; totalBalance: number; isBelowMinimum: boolean; version: number };
type Balance = { stockItemId: string; itemCode: string; itemName: string; unit: string; locationId: string; locationCode: string; locationName: string; balance: number; minimumLevel: number; isBelowMinimum: boolean };
type Movement = { id: string; itemCode: string; itemName: string; locationCode: string; employeeNo: string | null; employeeName: string | null; movementType: string; quantity: number; signedQuantity: number; source: string; occurredAt: string; note: string | null };
type Asset = { id: string; companyId: string; locationId: string | null; assetTag: string; name: string; category: string; serialNumber: string | null; status: string; purchaseCost: number | null; currency: string | null; assignedEmployeeId: string | null; assignedEmployeeNo: string | null; assignedEmployeeName: string | null; activeAssignmentId: string | null; version: number; assignmentVersion: number | null };
type Assignment = { id: string; assetId: string; assetTag: string; employeeId: string; employeeNo: string; employeeName: string; assignedDate: string; dueDate: string | null; returnedDate: string | null; status: string; note: string | null; version: number };

function todayLocal() { const d = new Date(); const o = d.getTimezoneOffset() * 60000; return new Date(d.getTime() - o).toISOString().slice(0,10); }
function nowLocalInput() { const d = new Date(); const o = d.getTimezoneOffset() * 60000; return new Date(d.getTime() - o).toISOString().slice(0,16); }
function assetStatus(value:string) { return value === "AVAILABLE" ? "Kullanıma hazır" : value === "ASSIGNED" ? "Zimmetli" : value === "MAINTENANCE" ? "Bakımda" : value === "LOST" ? "Kayıp" : value === "RETIRED" ? "Kullanım dışı" : value; }
function assignmentStatus(value:string) { return value === "ACTIVE" ? "Devam ediyor" : value === "RETURNED" ? "İade edildi" : value === "DAMAGED" ? "Hasarlı iade" : value === "LOST" ? "Kayıp" : value; }
function movementType(value:string) { return value === "RECEIPT" ? "Giriş" : value === "ISSUE" ? "Çıkış" : value === "RETURN" ? "İade" : value === "CORRECTION_IN" ? "Artı düzeltme" : value === "CORRECTION_OUT" ? "Eksi düzeltme" : value; }

export default function AssetsPage() {
  const [me,setMe]=useState<Me|null>(null), [companies,setCompanies]=useState<Company[]>([]), [employees,setEmployees]=useState<Employee[]>([]);
  const [companyId,setCompanyId]=useState(""), [locations,setLocations]=useState<Location[]>([]), [items,setItems]=useState<StockItem[]>([]), [balances,setBalances]=useState<Balance[]>([]), [movements,setMovements]=useState<Movement[]>([]), [assets,setAssets]=useState<Asset[]>([]), [assignments,setAssignments]=useState<Assignment[]>([]);
  const [message,setMessage]=useState("Zimmet ve stok verileri yükleniyor…"), [busy,setBusy]=useState(false);
  const permissions=useMemo(()=>new Set(me?.permissions.map(x=>x.code)??[]),[me]);
  const selectedCompany=companies.find(x=>x.id===companyId);
  const belowMinimum=balances.filter(x=>x.isBelowMinimum);
  const assignedAssets=assets.filter(x=>x.status==="ASSIGNED");
  const availableAssets=assets.filter(x=>x.status==="AVAILABLE");
  useEffect(()=>{void initialize();},[]);

  async function initialize(){ const current=await json<Me>("/api/v1/auth/me"); if(!current){window.location.replace("/login");return;} setMe(current); const rows=await json<Company[]>("/api/v1/organization/companies")??[]; setCompanies(rows); const id=rows[0]?.id??""; setCompanyId(id); if(id) await loadCompany(id); setMessage("Zimmet & Stok Merkezi hazır."); }
  async function loadCompany(id:string){ setCompanyId(id); const [ep,ls,is,bs,ms,as,hs]=await Promise.all([json<EmployeePage>(`/api/v1/personnel/employees?companyId=${id}&status=ACTIVE&pageSize=100`),json<Location[]>(`/api/v1/administration/stock/locations?companyId=${id}`),json<StockItem[]>(`/api/v1/administration/stock/items?companyId=${id}`),json<Balance[]>(`/api/v1/administration/stock/balances?companyId=${id}`),json<Movement[]>(`/api/v1/administration/stock/movements?companyId=${id}&take=100`),json<Asset[]>(`/api/v1/administration/assets?companyId=${id}`),json<Assignment[]>(`/api/v1/administration/asset-assignments?companyId=${id}`)]); setEmployees(ep?.items??[]);setLocations(ls??[]);setItems(is??[]);setBalances(bs??[]);setMovements(ms??[]);setAssets(as??[]);setAssignments(hs??[]); }
  async function refreshData(){ if(companyId) await loadCompany(companyId); }
  async function post(path:string,body:unknown,success:string){setBusy(true);try{const r=await authFetch(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!r?.ok){setMessage(await errorMessage(r,"İşlem tamamlanamadı."));return false;}setMessage(success);await refreshData();return true;}finally{setBusy(false);}}
  async function createLocation(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);if(await post("/api/v1/administration/stock/locations",{companyId,code:f.get("code"),name:f.get("name")},"Stok lokasyonu oluşturuldu."))e.currentTarget.reset();}
  async function createItem(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);if(await post("/api/v1/administration/stock/items",{companyId,code:f.get("code"),name:f.get("name"),unit:f.get("unit"),minimumLevel:Number(f.get("minimumLevel"))},"Stok kalemi oluşturuldu."))e.currentTarget.reset();}
  async function movement(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);if(await post("/api/v1/administration/stock/movements",{stockItemId:f.get("stockItemId"),locationId:f.get("locationId"),employeeId:f.get("employeeId")||null,movementType:f.get("movementType"),quantity:Number(f.get("quantity")),source:"MANUAL",externalEventId:null,note:f.get("note")||null,occurredAt:new Date(String(f.get("occurredAt"))).toISOString()},"Stok hareketi append-only deftere kaydedildi."))e.currentTarget.reset();}
  async function createAsset(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const cost=String(f.get("purchaseCost")??"");if(await post("/api/v1/administration/assets",{companyId,locationId:f.get("locationId")||null,assetTag:f.get("assetTag"),name:f.get("name"),category:f.get("category"),serialNumber:f.get("serialNumber")||null,purchaseDate:f.get("purchaseDate")||null,purchaseCost:cost?Number(cost):null,currency:cost?f.get("currency"):null,note:f.get("note")||null},"Demirbaş kartı oluşturuldu."))e.currentTarget.reset();}
  async function assign(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const assetId=String(f.get("assetId"));if(await post(`/api/v1/administration/assets/${assetId}/assign`,{assetId,employeeId:f.get("employeeId"),assignedDate:f.get("assignedDate"),dueDate:f.get("dueDate")||null,note:f.get("note")||null},"Demirbaş personele zimmetlendi."))e.currentTarget.reset();}
  async function returnAsset(a:Asset,damaged:boolean){if(a.assignmentVersion==null)return;await post(`/api/v1/administration/assets/${a.id}/return`,{assetVersion:a.version,assignmentVersion:a.assignmentVersion,returnedDate:todayLocal(),damaged,locationId:a.locationId},damaged?"Hasarlı iade kaydedildi; demirbaş bakım durumuna alındı.":"Demirbaş iade alındı.");}
  async function lost(a:Asset){if(a.assignmentVersion==null)return;await post(`/api/v1/administration/assets/${a.id}/lost`,{assetVersion:a.version,assignmentVersion:a.assignmentVersion,lostDate:todayLocal()},"Demirbaş kayıp olarak işaretlendi.");}
  async function json<T>(p:string):Promise<T|null>{const r=await authFetch(p);return r?.ok?await r.json() as T:null;}
  async function authFetch(p:string,i?:RequestInit):Promise<Response|null>{let t=sessionStorage.getItem("pp_access_token")??await refresh();if(!t)return null;let r=await fetch(`${apiBase}${p}`,{...i,headers:{...(i?.headers??{}),Authorization:`Bearer ${t}`},credentials:"include"});if(r.status!==401)return r;t=await refresh();if(!t)return r;return fetch(`${apiBase}${p}`,{...i,headers:{...(i?.headers??{}),Authorization:`Bearer ${t}`},credentials:"include"});}
  async function refresh():Promise<string|null>{try{const r=await fetch(`${apiBase}/api/v1/auth/refresh`,{method:"POST",credentials:"include"});if(!r.ok)return null;const b=await r.json() as AuthResponse;sessionStorage.setItem("pp_access_token",b.accessToken);return b.accessToken;}catch{return null;}}
  async function errorMessage(r:Response|null,f:string){if(!r)return f;const b=await r.json().catch(()=>null) as {error?:{code?:string;message?:string}}|null;return b?.error?.code?`${b.error.code}: ${b.error.message??f}`:b?.error?.message??f;}

  return <main className="page-shell">
    <PageHeader eyebrow="Zimmet ve stok" title="Varlık operasyonu" description="Stok seviyelerini, hareket kayıtlarını ve personel zimmetlerini şirket bazında yönetin." status={message}/>

    <section className="stat-grid" aria-label="Varlık özeti">
      <article className="stat-card"><span className="stat-icon"><Icon name="building"/></span><span className="stat-copy"><strong>{locations.length}</strong><span>Stok lokasyonu</span></span></article>
      <article className="stat-card"><span className="stat-icon"><Icon name="box"/></span><span className="stat-copy"><strong>{items.length}</strong><span>Stok kalemi</span></span></article>
      <article className="stat-card"><span className="stat-icon"><Icon name="bell"/></span><span className="stat-copy"><strong>{belowMinimum.length}</strong><span>Minimum altı bakiye</span></span></article>
      <article className="stat-card"><span className="stat-icon"><Icon name="people"/></span><span className="stat-copy"><strong>{assignedAssets.length}</strong><span>Aktif zimmet</span></span></article>
    </section>

    <section className="panel workspace-panel">
      <div className="workspace-copy"><span className="eyebrow dark">Çalışma kapsamı</span><h2>Şirket seçimi</h2><p>Lokasyonlar, stok bakiyeleri, hareketler ve demirbaşlar seçili şirkete göre güncellenir.</p></div>
      <label className="field-label workspace-select">Şirket<select value={companyId} onChange={e=>void loadCompany(e.target.value)}><option value="">Şirket seçin</option>{companies.map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></label>
    </section>

    <div className="content-stack">
      {permissions.has("administration.stock.manage")?<section className="organization-grid">
        <article className="panel"><div className="panel-heading"><div><span className="eyebrow dark">Stok tanımı</span><h2>Lokasyonlar</h2><p>Depo, ofis ve saha stok noktalarını yönetin.</p></div><strong>{locations.length}</strong></div><OperationDisclosure title="Yeni lokasyon ekle" description="Stok hareketlerinde kullanılacak yeni bir depo, ofis veya saha noktası oluşturun."><form className="stack" onSubmit={createLocation}><label className="field-label">Lokasyon kodu<input name="code" required/></label><label className="field-label">Lokasyon adı<input name="name" required/></label><button className="primary-button" disabled={busy||!companyId}>Lokasyonu kaydet</button></form></OperationDisclosure>{locations.length ? <div className="compact-list">{locations.map(x=><div className="role-row" key={x.id}><strong>{x.code}</strong><span>{x.name}</span></div>)}</div> : <p className="panel-description">Henüz lokasyon tanımlanmamış.</p>}</article>
        <article className="panel"><div className="panel-heading"><div><span className="eyebrow dark">Stok tanımı</span><h2>Stok kalemleri</h2><p>Takip edilen malzemeleri ve minimum seviyeleri yönetin.</p></div><strong>{items.length}</strong></div><OperationDisclosure title="Yeni stok kalemi ekle" description="Takip edilecek malzemeyi, ölçü birimini ve uyarı seviyesini tanımlayın."><form className="stack" onSubmit={createItem}><label className="field-label">Kalem kodu<input name="code" required/></label><label className="field-label">Kalem adı<input name="name" required/></label><label className="field-label">Ölçü birimi<input name="unit" defaultValue="ADET" required/></label><label className="field-label">Minimum seviye<input name="minimumLevel" type="number" min="0" step="0.001" defaultValue="0"/></label><button className="primary-button" disabled={busy||!companyId}>Kalemi kaydet</button></form></OperationDisclosure></article>
      </section>:null}

      {permissions.has("administration.stock.movement.record")?<section className="panel"><div className="panel-heading"><div><span className="eyebrow dark">Stok hareketi</span><h2>Giriş, çıkış veya düzeltme</h2><p>Her işlem değiştirilemeyen hareket defterine yeni bir kayıt olarak eklenir.</p></div></div><OperationDisclosure title="Yeni stok hareketi kaydet" description="Kalem, lokasyon ve hareket türünü seçerek stok bakiyesini güncelleyin."><form className="inline-form" onSubmit={movement}><label className="field-label">Stok kalemi<select name="stockItemId" required><option value="">Kalem seçin</option>{items.map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></label><label className="field-label">Lokasyon<select name="locationId" required><option value="">Lokasyon seçin</option>{locations.map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></label><label className="field-label">Hareket türü<select name="movementType" defaultValue="RECEIPT"><option value="RECEIPT">Stok girişi</option><option value="ISSUE">Stok çıkışı</option><option value="RETURN">İade</option><option value="CORRECTION_IN">Artı düzeltme</option><option value="CORRECTION_OUT">Eksi düzeltme</option></select></label><label className="field-label">Miktar<input name="quantity" type="number" min="0.001" step="0.001" required/></label><label className="field-label">İlgili personel<select name="employeeId"><option value="">Personel yok</option>{employees.map(x=><option key={x.id} value={x.id}>{x.employeeNo} · {x.firstName} {x.lastName}</option>)}</select></label><label className="field-label">İşlem zamanı<input name="occurredAt" type="datetime-local" defaultValue={nowLocalInput()} required/></label><label className="field-label">Not<input name="note"/></label><button className="primary-button" disabled={busy||!companyId}>Hareketi kaydet</button></form></OperationDisclosure></section>:null}

      {permissions.has("administration.stock.view")?<section className={`panel attention-panel ${belowMinimum.length ? "warning" : "success"}`}><div className="panel-heading"><div><span className="eyebrow dark">Stok görünümü</span><h2>Güncel bakiyeler</h2><p>{belowMinimum.length ? `${belowMinimum.length} bakiye minimum seviyenin altında.` : "Tüm bakiyeler tanımlı minimum seviyelerde veya üzerinde."}</p></div><strong>{balances.length}</strong></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Kalem</th><th>Lokasyon</th><th>Bakiye</th><th>Minimum</th><th>Durum</th></tr></thead><tbody>{balances.length?balances.map(x=><tr key={`${x.stockItemId}-${x.locationId}`}><td><strong>{x.itemName}</strong><small>{x.itemCode}</small></td><td>{x.locationCode} · {x.locationName}</td><td><strong>{x.balance.toLocaleString("tr-TR")} {x.unit}</strong></td><td>{x.minimumLevel.toLocaleString("tr-TR")}</td><td><span className={`status-badge ${x.isBelowMinimum?"danger":"success"}`}>{x.isBelowMinimum?"Minimum altı":"Yeterli"}</span></td></tr>):<tr><td className="empty-row" colSpan={5}>Henüz stok hareketi yok.</td></tr>}</tbody></table></div>
        <div className="panel-heading table-section-heading"><div><h2>Son hareketler</h2><p>En yeni stok işlemleri ilk sırada gösterilir.</p></div><strong>{movements.length}</strong></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Zaman</th><th>Kalem</th><th>Lokasyon</th><th>Tür</th><th>Miktar</th><th>Personel</th></tr></thead><tbody>{movements.length?movements.map(x=><tr key={x.id}><td>{new Date(x.occurredAt).toLocaleString("tr-TR")}</td><td>{x.itemCode} · {x.itemName}</td><td>{x.locationCode}</td><td><span className="status-badge">{movementType(x.movementType)}</span></td><td className={x.signedQuantity<0?"amount-negative":"amount-positive"}>{x.signedQuantity.toLocaleString("tr-TR")}</td><td>{x.employeeNo?`${x.employeeNo} · ${x.employeeName}`:"—"}</td></tr>):<tr><td className="empty-row" colSpan={6}>Henüz hareket kaydı yok.</td></tr>}</tbody></table></div></section>:null}

      {permissions.has("administration.asset.manage")||permissions.has("administration.asset.assign")?<section className="organization-grid">
        {permissions.has("administration.asset.manage")?<article className="panel"><div className="panel-heading"><div><span className="eyebrow dark">Demirbaş kartı</span><h2>Envantere demirbaş ekleyin</h2><p>Satın alma ve lokasyon bilgileriyle yeni varlık kaydı oluşturun.</p></div></div><OperationDisclosure title="Yeni demirbaş formunu aç" description="Varlık etiketi, kategori ve isteğe bağlı satın alma bilgilerini girin."><form className="stack" onSubmit={createAsset}><label className="field-label">Varlık etiketi<input name="assetTag" required/></label><label className="field-label">Demirbaş adı<input name="name" required/></label><label className="field-label">Kategori<input name="category" required/></label><label className="field-label">Seri numarası<input name="serialNumber"/></label><label className="field-label">Lokasyon<select name="locationId"><option value="">Lokasyon yok</option>{locations.map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></label><label className="field-label">Alış tarihi<input name="purchaseDate" type="date"/></label><label className="field-label">Alış maliyeti<input name="purchaseCost" type="number" min="0" step="0.01"/></label><label className="field-label">Para birimi<input name="currency" defaultValue={selectedCompany?.defaultCurrency??"TRY"}/></label><label className="field-label">Not<input name="note"/></label><button className="primary-button" disabled={busy||!companyId}>Demirbaşı kaydet</button></form></OperationDisclosure></article>:null}
        {permissions.has("administration.asset.assign")?<article className="panel"><div className="panel-heading"><div><span className="eyebrow dark">Zimmet işlemi</span><h2>Personele demirbaş atayın</h2><p>Yalnızca kullanıma hazır demirbaşlar seçilebilir.</p></div><strong>{availableAssets.length}</strong></div><OperationDisclosure title="Yeni zimmet başlat" description="Kullanıma hazır demirbaşı ve teslim alacak personeli seçin."><form className="stack" onSubmit={assign}><label className="field-label">Demirbaş<select name="assetId" required><option value="">Demirbaş seçin</option>{availableAssets.map(x=><option key={x.id} value={x.id}>{x.assetTag} · {x.name}</option>)}</select></label><label className="field-label">Personel<select name="employeeId" required><option value="">Personel seçin</option>{employees.map(x=><option key={x.id} value={x.id}>{x.employeeNo} · {x.firstName} {x.lastName}</option>)}</select></label><label className="field-label">Zimmet tarihi<input name="assignedDate" type="date" defaultValue={todayLocal()} required/></label><label className="field-label">Planlanan iade tarihi<input name="dueDate" type="date"/></label><label className="field-label">Not<input name="note"/></label><button className="primary-button" disabled={busy||!companyId}>Zimmeti başlat</button></form></OperationDisclosure></article>:null}
      </section>:null}

      {permissions.has("administration.asset.view")?<section className="panel"><div className="panel-heading"><div><span className="eyebrow dark">Demirbaş envanteri</span><h2>Varlıklar ve zimmet durumu</h2><p>Aktif zimmetleri iade, hasarlı iade veya kayıp işlemiyle sonuçlandırın.</p></div><strong>{assets.length}</strong></div><div className="table-wrap responsive-table-wrap" role="region" aria-label="Demirbaş envanteri" tabIndex={0}><table className="data-table responsive-table"><thead><tr><th>Etiket</th><th>Demirbaş</th><th>Durum</th><th>Zimmetli personel</th><th>İşlem</th></tr></thead><tbody>{assets.length?assets.map(a=><tr key={a.id}><td data-label="Etiket"><strong>{a.assetTag}</strong></td><td data-label="Demirbaş">{a.name}<small>{a.serialNumber??a.category}</small></td><td data-label="Durum"><span className={`status-badge ${a.status==="AVAILABLE"?"success":a.status==="LOST"?"danger":a.status==="MAINTENANCE"?"warning":""}`}>{assetStatus(a.status)}</span></td><td data-label="Zimmetli personel">{a.assignedEmployeeNo?`${a.assignedEmployeeNo} · ${a.assignedEmployeeName}`:"—"}</td><td data-label="İşlem">{a.status==="ASSIGNED"&&permissions.has("administration.asset.assign")?<div className="action-row"><button className="secondary-button button-success" onClick={()=>void returnAsset(a,false)}>İade al</button><button className="secondary-button" onClick={()=>void returnAsset(a,true)}>Hasarlı iade</button><button className="secondary-button button-danger" onClick={()=>void lost(a)}>Kayıp</button></div>:"—"}</td></tr>):<tr><td className="empty-row" colSpan={5}>Henüz demirbaş kaydı yok.</td></tr>}</tbody></table></div>
        <div className="panel-heading table-section-heading"><div><h2>Zimmet geçmişi</h2><p>Tamamlanan ve devam eden tüm zimmet hareketleri.</p></div><strong>{assignments.length}</strong></div><div className="table-wrap responsive-table-wrap" role="region" aria-label="Zimmet geçmişi" tabIndex={0}><table className="data-table responsive-table"><thead><tr><th>Etiket</th><th>Personel</th><th>Zimmet tarihi</th><th>İade tarihi</th><th>Durum</th></tr></thead><tbody>{assignments.length?assignments.map(x=><tr key={x.id}><td data-label="Etiket"><strong>{x.assetTag}</strong></td><td data-label="Personel">{x.employeeNo} · {x.employeeName}</td><td data-label="Zimmet tarihi">{new Date(`${x.assignedDate}T00:00:00`).toLocaleDateString("tr-TR")}</td><td data-label="İade tarihi">{x.returnedDate?new Date(`${x.returnedDate}T00:00:00`).toLocaleDateString("tr-TR"):"—"}</td><td data-label="Durum"><span className={`status-badge ${x.status==="ACTIVE"?"success":x.status==="LOST"?"danger":""}`}>{assignmentStatus(x.status)}</span></td></tr>):<tr><td className="empty-row" colSpan={5}>Henüz zimmet geçmişi yok.</td></tr>}</tbody></table></div></section>:null}
    </div>
  </main>;
}
