"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

const apiBase = process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://localhost:8080";
type Permission = { code: string };
type Me = { permissions: Permission[] };
type AuthResponse = { accessToken: string; accessTokenExpiresAt: string };
type Company = { id: string; code: string; name: string; defaultCurrency: string };
type Employee = { id: string; companyId: string; employeeNo: string; firstName: string; lastName: string; status: string };
type EmployeePage = { items: Employee[] };
type Location = { id: string; companyId: string; code: string; name: string; isActive: boolean; version: number };
type StockItem = { id: string; companyId: string; code: string; name: string; unit: string; minimumLevel: number; totalBalance: number; isBelowMinimum: boolean; version: number };
type Balance = { stockItemId: string; itemCode: string; itemName: string; unit: string; locationId: string; locationCode: string; locationName: string; balance: number; minimumLevel: number; isBelowMinimum: boolean };
type Movement = { id: string; itemCode: string; itemName: string; locationCode: string; employeeNo: string | null; employeeName: string | null; movementType: string; quantity: number; signedQuantity: number; source: string; occurredAt: string; note: string | null };
type Asset = { id: string; companyId: string; locationId: string | null; assetTag: string; name: string; category: string; serialNumber: string | null; status: string; purchaseCost: number | null; currency: string | null; assignedEmployeeId: string | null; assignedEmployeeNo: string | null; assignedEmployeeName: string | null; activeAssignmentId: string | null; version: number; assignmentVersion: number | null };
type Assignment = { id: string; assetId: string; assetTag: string; employeeId: string; employeeNo: string; employeeName: string; assignedDate: string; dueDate: string | null; returnedDate: string | null; status: string; note: string | null; version: number };

function todayLocal() { const d = new Date(); const o = d.getTimezoneOffset() * 60000; return new Date(d.getTime() - o).toISOString().slice(0,10); }
function nowLocalInput() { const d = new Date(); const o = d.getTimezoneOffset() * 60000; return new Date(d.getTime() - o).toISOString().slice(0,16); }

export default function AssetsPage() {
  const [me,setMe]=useState<Me|null>(null), [companies,setCompanies]=useState<Company[]>([]), [employees,setEmployees]=useState<Employee[]>([]);
  const [companyId,setCompanyId]=useState(""), [locations,setLocations]=useState<Location[]>([]), [items,setItems]=useState<StockItem[]>([]), [balances,setBalances]=useState<Balance[]>([]), [movements,setMovements]=useState<Movement[]>([]), [assets,setAssets]=useState<Asset[]>([]), [assignments,setAssignments]=useState<Assignment[]>([]);
  const [message,setMessage]=useState("Zimmet ve stok verileri yükleniyor…"), [busy,setBusy]=useState(false);
  const permissions=useMemo(()=>new Set(me?.permissions.map(x=>x.code)??[]),[me]); const selectedCompany=companies.find(x=>x.id===companyId);
  useEffect(()=>{void initialize();},[]);

  async function initialize(){ const current=await json<Me>("/api/v1/auth/me"); if(!current){window.location.replace("/login");return;} setMe(current); const rows=await json<Company[]>("/api/v1/organization/companies")??[]; setCompanies(rows); const id=rows[0]?.id??""; setCompanyId(id); if(id) await loadCompany(id); setMessage("Zimmet & Stok Merkezi hazır."); }
  async function loadCompany(id:string){ setCompanyId(id); const [ep,ls,is,bs,ms,as,hs]=await Promise.all([json<EmployeePage>(`/api/v1/personnel/employees?companyId=${id}&status=ACTIVE&pageSize=100`),json<Location[]>(`/api/v1/administration/stock/locations?companyId=${id}`),json<StockItem[]>(`/api/v1/administration/stock/items?companyId=${id}`),json<Balance[]>(`/api/v1/administration/stock/balances?companyId=${id}`),json<Movement[]>(`/api/v1/administration/stock/movements?companyId=${id}&take=100`),json<Asset[]>(`/api/v1/administration/assets?companyId=${id}`),json<Assignment[]>(`/api/v1/administration/asset-assignments?companyId=${id}`)]); setEmployees(ep?.items??[]);setLocations(ls??[]);setItems(is??[]);setBalances(bs??[]);setMovements(ms??[]);setAssets(as??[]);setAssignments(hs??[]); }
  async function refreshData(){ if(companyId) await loadCompany(companyId); }
  async function post(path:string,body:unknown,success:string){setBusy(true);try{const r=await authFetch(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!r?.ok){setMessage(await errorMessage(r,"İşlem tamamlanamadı."));return false;}setMessage(success);await refreshData();return true;}finally{setBusy(false);}}
  async function createLocation(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);if(await post("/api/v1/administration/stock/locations",{companyId,code:f.get("code"),name:f.get("name")},"Stok lokasyonu oluşturuldu."))e.currentTarget.reset();}
  async function createItem(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);if(await post("/api/v1/administration/stock/items",{companyId,code:f.get("code"),name:f.get("name"),unit:f.get("unit"),minimumLevel:Number(f.get("minimumLevel"))},"Stok kalemi oluşturuldu."))e.currentTarget.reset();}
  async function movement(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);if(await post("/api/v1/administration/stock/movements",{stockItemId:f.get("stockItemId"),locationId:f.get("locationId"),employeeId:f.get("employeeId")||null,movementType:f.get("movementType"),quantity:Number(f.get("quantity")),source:"MANUAL",externalEventId:null,note:f.get("note")||null,occurredAt:new Date(String(f.get("occurredAt"))).toISOString()},"Stok hareketi append-only deftere kaydedildi."))e.currentTarget.reset();}
  async function createAsset(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const cost=String(f.get("purchaseCost")??"");if(await post("/api/v1/administration/assets",{companyId,locationId:f.get("locationId")||null,assetTag:f.get("assetTag"),name:f.get("name"),category:f.get("category"),serialNumber:f.get("serialNumber")||null,purchaseDate:f.get("purchaseDate")||null,purchaseCost:cost?Number(cost):null,currency:cost?f.get("currency"):null,note:f.get("note")||null},"Demirbaş kartı oluşturuldu."))e.currentTarget.reset();}
  async function assign(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const assetId=String(f.get("assetId"));if(await post(`/api/v1/administration/assets/${assetId}/assign`,{assetId,employeeId:f.get("employeeId"),assignedDate:f.get("assignedDate"),dueDate:f.get("dueDate")||null,note:f.get("note")||null},"Demirbaş personele zimmetlendi."))e.currentTarget.reset();}
  async function returnAsset(a:Asset,damaged:boolean){if(a.assignmentVersion==null)return;await post(`/api/v1/administration/assets/${a.id}/return`,{assetVersion:a.version,assignmentVersion:a.assignmentVersion,returnedDate:todayLocal(),damaged,locationId:a.locationId},damaged?"Hasarlı iade kaydedildi; demirbaş bakım durumuna alındı.":"Demirbaş iade alındı.");}
  async function lost(a:Asset){if(a.assignmentVersion==null)return;await post(`/api/v1/administration/assets/${a.id}/lost`,{assetVersion:a.version,assignmentVersion:a.assignmentVersion,lostDate:todayLocal()},"Demirbaş kayıp olarak işaretlendi.");}
  async function json<T>(p:string):Promise<T|null>{const r=await authFetch(p);return r?.ok?await r.json() as T:null;}
  async function authFetch(p:string,i?:RequestInit):Promise<Response|null>{let t=sessionStorage.getItem("pp_access_token")??await refresh();if(!t)return null;let r=await fetch(`${apiBase}${p}`,{...i,headers:{...(i?.headers??{}),Authorization:`Bearer ${t}`},credentials:"include"});if(r.status!==401)return r;t=await refresh();if(!t)return r;return fetch(`${apiBase}${p}`,{...i,headers:{...(i?.headers??{}),Authorization:`Bearer ${t}`},credentials:"include"});}
  async function refresh():Promise<string|null>{try{const r=await fetch(`${apiBase}/api/v1/auth/refresh`,{method:"POST",credentials:"include"});if(!r.ok)return null;const b=await r.json() as AuthResponse;sessionStorage.setItem("pp_access_token",b.accessToken);return b.accessToken;}catch{return null;}}
  async function errorMessage(r:Response|null,f:string){if(!r)return f;const b=await r.json().catch(()=>null) as {error?:{code?:string;message?:string}}|null;return b?.error?.code?`${b.error.code}: ${b.error.message??f}`:b?.error?.message??f;}

  return <main className="shell"><a className="back" href="/dashboard">← Dashboard</a><section className="hero compact"><span className="eyebrow">SPRINT 9 · İDARİ İŞLER</span><h1>Zimmet & Stok Merkezi</h1><p>{message}</p></section>
  <section className="panel"><label className="field-label">Şirket<select value={companyId} onChange={e=>void loadCompany(e.target.value)}><option value="">Seçin</option>{companies.map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></label></section>
  {permissions.has("administration.stock.manage")?<section className="organization-grid"><article className="panel"><h2>Stok lokasyonu</h2><form className="inline-form" onSubmit={createLocation}><label className="field-label">Kod<input name="code" required/></label><label className="field-label">Ad<input name="name" required/></label><button className="primary-button" disabled={busy||!companyId}>Ekle</button></form><div className="compact-list">{locations.map(x=><div key={x.id}>{x.code} · {x.name}</div>)}</div></article><article className="panel"><h2>Stok kalemi</h2><form className="inline-form" onSubmit={createItem}><label className="field-label">Kod<input name="code" required/></label><label className="field-label">Ad<input name="name" required/></label><label className="field-label">Birim<input name="unit" defaultValue="EA" required/></label><label className="field-label">Minimum<input name="minimumLevel" type="number" min="0" step="0.001" defaultValue="0"/></label><button className="primary-button" disabled={busy||!companyId}>Ekle</button></form></article></section>:null}
  {permissions.has("administration.stock.movement.record")?<section className="panel"><h2>Append-only stok hareketi</h2><form className="inline-form" onSubmit={movement}><label className="field-label">Kalem<select name="stockItemId" required><option value="">Seçin</option>{items.map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></label><label className="field-label">Lokasyon<select name="locationId" required><option value="">Seçin</option>{locations.map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></label><label className="field-label">Tip<select name="movementType" defaultValue="RECEIPT"><option>RECEIPT</option><option>ISSUE</option><option>RETURN</option><option>CORRECTION_IN</option><option>CORRECTION_OUT</option></select></label><label className="field-label">Miktar<input name="quantity" type="number" min="0.001" step="0.001" required/></label><label className="field-label">Personel<select name="employeeId"><option value="">—</option>{employees.map(x=><option key={x.id} value={x.id}>{x.employeeNo} · {x.firstName} {x.lastName}</option>)}</select></label><label className="field-label">Zaman<input name="occurredAt" type="datetime-local" defaultValue={nowLocalInput()} required/></label><label className="field-label">Not<input name="note"/></label><button className="primary-button" disabled={busy}>Hareket kaydet</button></form></section>:null}
  {permissions.has("administration.stock.view")?<section className="panel"><h2>Stok bakiyesi</h2><div className="table-wrap"><table className="data-table"><thead><tr><th>Kalem</th><th>Lokasyon</th><th>Bakiye</th><th>Minimum</th><th>Durum</th></tr></thead><tbody>{balances.length?balances.map(x=><tr key={`${x.stockItemId}-${x.locationId}`}><td>{x.itemCode} · {x.itemName}</td><td>{x.locationCode} · {x.locationName}</td><td><strong>{x.balance} {x.unit}</strong></td><td>{x.minimumLevel}</td><td>{x.isBelowMinimum?"MİNİMUM ALTI":"OK"}</td></tr>):<tr><td colSpan={5}>Henüz hareket yok.</td></tr>}</tbody></table></div><h3>Son hareketler</h3><div className="table-wrap"><table className="data-table"><thead><tr><th>Zaman</th><th>Kalem</th><th>Lokasyon</th><th>Tip</th><th>Miktar</th><th>Personel</th></tr></thead><tbody>{movements.map(x=><tr key={x.id}><td>{new Date(x.occurredAt).toLocaleString()}</td><td>{x.itemCode}</td><td>{x.locationCode}</td><td>{x.movementType}</td><td>{x.signedQuantity}</td><td>{x.employeeNo?`${x.employeeNo} · ${x.employeeName}`:"—"}</td></tr>)}</tbody></table></div></section>:null}
  {permissions.has("administration.asset.manage")?<section className="panel"><h2>Yeni demirbaş</h2><form className="inline-form" onSubmit={createAsset}><label className="field-label">Etiket<input name="assetTag" required/></label><label className="field-label">Ad<input name="name" required/></label><label className="field-label">Kategori<input name="category" required/></label><label className="field-label">Seri no<input name="serialNumber"/></label><label className="field-label">Lokasyon<select name="locationId"><option value="">—</option>{locations.map(x=><option key={x.id} value={x.id}>{x.code}</option>)}</select></label><label className="field-label">Alış tarihi<input name="purchaseDate" type="date"/></label><label className="field-label">Alış maliyeti<input name="purchaseCost" type="number" min="0" step="0.01"/></label><label className="field-label">Döviz<input name="currency" defaultValue={selectedCompany?.defaultCurrency??"TRY"}/></label><label className="field-label">Not<input name="note"/></label><button className="primary-button" disabled={busy}>Demirbaş oluştur</button></form></section>:null}
  {permissions.has("administration.asset.assign")?<section className="panel"><h2>Personele zimmet</h2><form className="inline-form" onSubmit={assign}><label className="field-label">Demirbaş<select name="assetId" required><option value="">Seçin</option>{assets.filter(x=>x.status==="AVAILABLE").map(x=><option key={x.id} value={x.id}>{x.assetTag} · {x.name}</option>)}</select></label><label className="field-label">Personel<select name="employeeId" required><option value="">Seçin</option>{employees.map(x=><option key={x.id} value={x.id}>{x.employeeNo} · {x.firstName} {x.lastName}</option>)}</select></label><label className="field-label">Zimmet tarihi<input name="assignedDate" type="date" defaultValue={todayLocal()} required/></label><label className="field-label">İade tarihi planı<input name="dueDate" type="date"/></label><label className="field-label">Not<input name="note"/></label><button className="primary-button" disabled={busy}>Zimmetle</button></form></section>:null}
  {permissions.has("administration.asset.view")?<section className="panel"><h2>Demirbaşlar</h2><div className="table-wrap"><table className="data-table"><thead><tr><th>Etiket</th><th>Demirbaş</th><th>Durum</th><th>Zimmetli personel</th><th>İşlem</th></tr></thead><tbody>{assets.map(a=><tr key={a.id}><td>{a.assetTag}</td><td>{a.name}<br/>{a.serialNumber??""}</td><td><strong>{a.status}</strong></td><td>{a.assignedEmployeeNo?`${a.assignedEmployeeNo} · ${a.assignedEmployeeName}`:"—"}</td><td>{a.status==="ASSIGNED"&&permissions.has("administration.asset.assign")?<div className="actions action-row"><button className="secondary-button" onClick={()=>void returnAsset(a,false)}>İade</button><button className="secondary-button" onClick={()=>void returnAsset(a,true)}>Hasarlı iade</button><button className="secondary-button" onClick={()=>void lost(a)}>Kayıp</button></div>:"—"}</td></tr>)}</tbody></table></div><h3>Zimmet geçmişi</h3><div className="table-wrap"><table className="data-table"><thead><tr><th>Etiket</th><th>Personel</th><th>Zimmet</th><th>İade</th><th>Durum</th></tr></thead><tbody>{assignments.map(x=><tr key={x.id}><td>{x.assetTag}</td><td>{x.employeeNo} · {x.employeeName}</td><td>{x.assignedDate}</td><td>{x.returnedDate??"—"}</td><td>{x.status}</td></tr>)}</tbody></table></div></section>:null}
  </main>;
}
