using Microsoft.AspNetCore.Diagnostics.HealthChecks;
using PersonnelPlatform.Api;
using PersonnelPlatform.Api.Attendance;
using PersonnelPlatform.Api.Auth;
using PersonnelPlatform.Api.Authorization;
using PersonnelPlatform.Api.Documents;
using PersonnelPlatform.Api.Leave;
using PersonnelPlatform.Api.Middleware;
using PersonnelPlatform.Api.Organization;
using PersonnelPlatform.Api.Personnel;
using PersonnelPlatform.Api.Security;
using PersonnelPlatform.Application.Attendance;
using PersonnelPlatform.Application.Documents;
using PersonnelPlatform.Application.Identity;
using PersonnelPlatform.Application.Leave;
using PersonnelPlatform.Application.Organization;
using PersonnelPlatform.Application.Personnel;
using PersonnelPlatform.Infrastructure;
using PersonnelPlatform.Infrastructure.Authorization;
using PersonnelPlatform.Infrastructure.Identity;
using PersonnelPlatform.Infrastructure.Persistence;

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddOpenApi();
builder.Services.AddInfrastructure(builder.Configuration);
builder.Services.AddIdentityInfrastructure(builder.Configuration);
builder.Services.AddAuthorizationInfrastructure();
builder.Services.AddScoped<AuthService>();
builder.Services.AddScoped<OrganizationService>();
builder.Services.AddScoped<PersonnelService>();
builder.Services.AddScoped<DocumentService>();
builder.Services.AddScoped<DocumentIntelligenceService>();
builder.Services.AddScoped<DocumentHistoryService>();
builder.Services.AddScoped<LeaveService>();
builder.Services.AddScoped<LeaveApprovalService>();
builder.Services.AddScoped<LeaveAttachmentService>();
builder.Services.AddScoped<AttendanceSetupService>();
builder.Services.AddPlatformAuthentication(builder.Configuration);
builder.Services.AddPlatformPermissionAuthorization();
builder.Services.AddCors(options => options.AddPolicy("development", policy => policy.WithOrigins("http://localhost:3000").AllowAnyHeader().AllowAnyMethod().AllowCredentials()));

var app = builder.Build();
app.UseMiddleware<CorrelationIdMiddleware>();
app.UseMiddleware<ApiExceptionMiddleware>();
if (app.Environment.IsDevelopment())
{
    app.UseCors("development");
    app.MapOpenApi();
    await app.Services.ApplyMigrationsAsync();
    await app.Services.SeedDevelopmentIdentityAsync(app.Configuration);
}
app.UseAuthentication();
app.UseAuthorization();
app.MapHealthChecks("/health/live", new HealthCheckOptions { Predicate = _ => false, ResponseWriter = HealthResponseWriter.WriteAsync });
app.MapHealthChecks("/health/ready", new HealthCheckOptions { Predicate = registration => registration.Tags.Contains("ready"), ResponseWriter = HealthResponseWriter.WriteAsync });
app.MapGet("/api/v1/system/ping", (HttpContext context) => Results.Ok(new { service = "PersonnelPlatform.Api", status = "ok", utc = DateTimeOffset.UtcNow, traceId = context.TraceIdentifier }));
app.MapIdentityEndpoints();
app.MapSecurityEndpoints();
app.MapOrganizationEndpoints();
app.MapPersonnelEndpoints();
app.MapDocumentEndpoints();
app.MapDocumentIntelligenceEndpoints();
app.MapDocumentHistoryEndpoints();
app.MapLeaveEndpoints();
app.MapLeaveApprovalEndpoints();
app.MapAttendanceSetupEndpoints();
await app.RunAsync();
public partial class Program;
